"""Pydantic schemas for the AR Collection Agent.

Defines the data models for AR customers, collection actions,
and the overall collection plan produced by the aging-bucket state machine.
"""

from typing import List, Literal, Optional

from pydantic import BaseModel, Field


class ARCustomer(BaseModel):
    """Represents a single accounts-receivable customer record."""

    customer_id: str = Field(description="Unique identifier for the customer.")
    customer_name: str = Field(description="Legal name of the customer entity.")
    invoice_number: str = Field(description="Invoice reference number.")
    invoice_date: str = Field(description="Date the invoice was issued (YYYY-MM-DD).")
    due_date: str = Field(description="Payment due date (YYYY-MM-DD).")
    outstanding_amount: float = Field(
        description="Amount still outstanding on the invoice in the invoice currency."
    )
    currency: str = Field(default="USD", description="Currency code, e.g. USD.")
    days_overdue: int = Field(
        description="Number of calendar days the invoice is past its due date."
    )
    prior_contact_count: int = Field(
        default=0,
        description="Number of prior collection contact attempts made for this invoice.",
    )
    credit_limit: float = Field(
        description="Approved credit limit for the customer account."
    )
    total_exposure: float = Field(
        description="Total outstanding balance across all open invoices for this customer."
    )


class CollectionAction(BaseModel):
    """Collection action and letter generated for a single AR customer."""

    customer_id: str = Field(description="Customer identifier, matches ARCustomer.customer_id.")
    aging_bucket: Literal["current", "1_30", "31_60", "61_90", "90_plus"] = Field(
        description=(
            "Aging bucket assigned deterministically from days_overdue: "
            "current=0 days, 1_30=1-30 days, 31_60=31-60 days, "
            "61_90=61-90 days, 90_plus=91+ days."
        )
    )
    escalation_tier: Literal[
        "no_action", "friendly_reminder", "formal_notice", "final_demand", "legal_referral"
    ] = Field(
        description=(
            "Escalation tier mapped directly from the aging bucket: "
            "no_action for current, friendly_reminder for 1_30, "
            "formal_notice for 31_60, final_demand for 61_90, "
            "legal_referral for 90_plus."
        )
    )
    collection_letter: str = Field(
        description=(
            "Tone-calibrated collection letter or internal memo generated by the LLM "
            "for this customer and escalation tier."
        )
    )
    credit_hold_recommended: bool = Field(
        description=(
            "True if a credit hold is recommended: triggered when days_overdue > 90 "
            "or total_exposure exceeds 80% of the customer credit limit."
        )
    )
    credit_hold_rationale: Optional[str] = Field(
        default=None,
        description="Explanation for why a credit hold is recommended, or None if not recommended.",
    )
    priority_score: int = Field(
        description=(
            "Numeric priority score from 1 (lowest) to 10 (highest), "
            "calculated from days_overdue and outstanding_amount. "
            "Drives sort order in the collection plan."
        )
    )


class CollectionPlan(BaseModel):
    """Complete AR collection plan produced for a given run date."""

    as_of_date: str = Field(description="The date the collection plan was generated (YYYY-MM-DD).")
    total_ar_outstanding: float = Field(
        description="Sum of outstanding_amount across all customers in this plan."
    )
    actions: List[CollectionAction] = Field(
        description="Collection actions for each customer, sorted by priority_score descending."
    )
    credit_hold_count: int = Field(
        description="Number of customers for whom a credit hold is recommended."
    )
    legal_referral_count: int = Field(
        description="Number of customers escalated to the legal_referral tier."
    )
    collection_summary: str = Field(
        description=(
            "Human-readable summary of the collection plan including total AR, "
            "number of accounts by tier, and recommended next steps."
        )
    )
